// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/orders': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders.post').default>>>>
    }
    '/api/payments/chip/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/chip/[id].get').default>>>>
    }
    '/api/payments/chip/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/chip/callback.post').default>>>>
    }
    '/api/payments/chip/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/chip/create.post').default>>>>
    }
    '/api/payments/chip/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/chip/test.get').default>>>>
    }
    '/api/payments/chip/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/chip/webhook.post').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}