// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/24/2025, 10:35:27 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/hassan/Documents/GitHub/tabby/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/plugins/**/*.{js,ts,mjs}","/Users/hassan/Documents/GitHub/tabby/composables/**/*.{js,ts,mjs}","/Users/hassan/Documents/GitHub/tabby/utils/**/*.{js,ts,mjs}","/Users/hassan/Documents/GitHub/tabby/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hassan/Documents/GitHub/tabby/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;