// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/9/2025, 11:20:33 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/adam/Documents/GitHub/shop-teknopuri/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/plugins/**/*.{js,ts,mjs}","/Users/adam/Documents/GitHub/shop-teknopuri/composables/**/*.{js,ts,mjs}","/Users/adam/Documents/GitHub/shop-teknopuri/utils/**/*.{js,ts,mjs}","/Users/adam/Documents/GitHub/shop-teknopuri/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/adam/Documents/GitHub/shop-teknopuri/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;